# Generated by Django 3.2.8 on 2023-06-07 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ontempleado',
            fields=[
                ('empleadoid', models.AutoField(db_column='empleadoId', primary_key=True, serialize=False)),
                ('primernombre', models.CharField(db_column='primerNombre', max_length=100)),
                ('segundonombre', models.CharField(blank=True, db_column='segundoNombre', max_length=100, null=True)),
                ('primerapellido', models.CharField(db_column='primerApellido', max_length=100)),
                ('segundoapellido', models.CharField(blank=True, db_column='segundoApellido', max_length=100, null=True)),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'ONTEmpleado',
                'managed': False,
            },
        ),
    ]
